name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:11-slim
    steps:
        - name: Install git on container
          run: |
            apt-get update
            apt-get install -y git --no-install-recommends

        - name: Checkout Project
          uses: actions/checkout@v4
          with:
            set-safe-directory: '*'

        - name: Checkout submodules
          run: |
            git config --global --add safe.directory *
            git submodule update --init --recursive
        
        - name: Run
          run: 
            pwd &&
            ls -la &&
            mkdir /accelerator &&
            cp * /accelerator -Rfv ;
            cd /accelerator &&
            bash ./cicd/_accelerator_docker_build_internal.sh
