name: Accelerator CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - overhaul
  push:
    branches:
      - master
      - overhaul

jobs:

  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-20.04', 'windows-2019', 'ubuntu-latest', 'windows-latest' ]
        include:
          - os: ubuntu-20.04
            cc: clang-8
            cxx: clang++-8
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
            upload: true
            upload-artifact-name: accelerator_linux
          - os: windows-2019
            cc: msvc
            cxx: msvc
          - os: windows-latest
            cc: msvc
            cxx: msvc
            upload: true
            upload-artifact-name: accelerator_windows

    uses: ./.github/workflows/build-extension.yml
    with:
      os: ${{ matrix.os }}
      cc: ${{ matrix.cc }}
      cxx: ${{ matrix.cxx }}
      upload: ${{ matrix.upload }}